env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - 'prettier'
  - '@typescript-eslint'
rules:
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never

  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - specs/**
      optionalDependencies: false
      peerDependencies: false
overrides:
  - files:
      - 'specs/**/*.ts'
    rules:
      no-unused-expressions: 'off'
settings:
  'import/resolver': { node: { extensions: ['.js', '.jsx', '.ts', '.tsx'] } }
